# Generated by Django 3.1.4 on 2021-01-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_token_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='firstUsed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
