# Generated by Django 3.1.4 on 2021-01-05 11:10

import accounts.models
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210105_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identifier',
            name='id',
            field=models.CharField(default=functools.partial(accounts.models.generateString, *(13,), **{}), editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
