# Generated by Django 3.1.4 on 2021-01-05 11:21

import accounts.models
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210105_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='secret',
            field=models.CharField(default=functools.partial(accounts.models.generateString, *(13,), **{}), editable=False, max_length=255),
        ),
    ]
